apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker
  namespace: arun
  labels:
    app: arun
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arun
  template:
    metadata:
      labels:
        app: arun
    spec:
      containers:
        - name: dotnet
          image: acrcontainer28.azurecr.io/acrcontainer28:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
      imagePullSecrets:
        - name: nikitha
