apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker
  namespace: arun
  labels:
    app: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: myapp
    spec:
      serviceAccountName: myapp-serviceaccount
      containers:
      - name: dockerdep-10-app
        image: arunbachi/b1:1
        resources:
          requests:
            cpu: 100m
            memory: 300Mi
          limits:
            cpu: 200m
            memory: 300Mi
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readiness
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 5
        env:
        - name: ENV_VARIABLE_NAME
          valueFrom:
            configMapKeyRef:
              name: myapp-config
              key: your_key_from_configmap