apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker
  labels:
    app: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: dotnet-aks:1.0.0
        image: arunbachi/dotnet-aks:1.0.0
        ports:
        - containerPort: 80