apiVersion: v5.0.1
kind: Service
metadata:
  name: docker
spec:
  selector:
    app: arun
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
  imagePullSecrets:
    - name: arun
